api:
  name: 'API: @project.name@'
  description: '@project.description@'
  version: '@project.version@'
server:
  port: 8081
  servlet:
    context-path: /nft-engine
spring:
  profiles:
    active: prod
  application:
    name: nft-engine
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/
    username: postgres
    password: root
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root